# -*- coding: utf-8 -*-
"""AI2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfFaewPebpQhHMZPAgqwV1RfRLJONG9B
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
print(torch.cuda.is_available())  # True nếu GPU được kích hoạt
print(torch.cuda.get_device_name(0))  # Tên GPU, ví dụ: Tesla T4

# Import các thư viện cần thiết
from PIL import Image
import torch
from transformers import CLIPProcessor, CLIPModel
import os
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model = CLIPModel.from_pretrained("/content/drive/MyDrive/clip_flickr8k_finetuned").to(device)
processor = CLIPProcessor.from_pretrained("/content/drive/MyDrive/clip_flickr8k_finetuned")

"""Chuẩn hóa ảnh (Normalization)
Đây là chuẩn hóa ảnh giống như CLIP đã được huấn luyện.

Nó giúp vector ảnh đầu ra nằm trong không gian giống như lúc train model.

ToTensor() chuyển ảnh → tensor PyTorch

Normalize() chuẩn hóa giá trị pixel theo mean/std chuẩn CLIP.
"""

from torchvision import transforms

CLIP_MEAN = [0.48145466, 0.4578275, 0.40821073]
CLIP_STD = [0.26862954, 0.26130258, 0.27577711]

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=CLIP_MEAN, std=CLIP_STD),
])

# Hàm trích xuất vector từ ảnh
def extract_image_features(image_path):
    image = Image.open(image_path) #.convert('RGB')
    image_tensor = transform(image).unsqueeze(0).to(device)
    with torch.no_grad():
      image_features = model.get_image_features(pixel_values=image_tensor)

    image_features = image_features / image_features.norm(p=2, dim=-1, keepdim=True)
    return image_features.cpu().numpy()

# Đường dẫn đến thư mục chứa ảnh trên Google Drive
image_dir = "/content/drive/MyDrive/text_img/imgresize/"
output_file = "/content/drive/MyDrive/text_img/image_vectors.npy"

# Xử lý tất cả ảnh và lưu vector
image_features_dict = {}
for filename in os.listdir(image_dir):
  file_path = os.path.join(image_dir, filename)
  if file_path.endswith((".jpg", ".png", ".jpeg")):
      try:
          feature = extract_image_features(file_path)
          image_features_dict[file_path] = feature
          if len(image_features_dict) % 100 == 0:  # In tiến độ sau mỗi 100 ảnh
              print(f"Processed {len(image_features_dict)} images")
      except Exception as e:
          print(f"Error processing {file_path}: {e}")
# Lưu kết quả vào file .npy trên Google Drive
np.save(output_file, image_features_dict)
print(f"Completed! Saved {len(image_features_dict)} image vectors to {output_file}")

# xử lý vecto text
def extract_text_features(query):
    inputs = processor(text=[query], return_tensors="pt", padding=True).to(device)
    with torch.no_grad():
        text_features = model.get_text_features(**inputs)
    text_features = text_features / text_features.norm(p=2, dim=-1, keepdim=True)
    return text_features.cpu().numpy()

loaded = np.load("/content/drive/MyDrive/text_img/image_vectors.npy", allow_pickle=True).item()

print("Số ảnh:", len(loaded))
print("Một key thử:", list(loaded.keys())[:5])

def cosine_similarity(a, b):
    a = np.array(a).squeeze()
    b = np.array(b).squeeze()
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

scores = []
query_vec = extract_text_features("A boy jumping in a fountain ")
for img_path, img_vec in loaded.items():
    img_vec = img_vec.reshape(1, -1)
    score = float(cosine_similarity([img_vec], [query_vec]))
    scores.append((img_path, score))

# Sắp xếp giảm dần
scores.sort(key=lambda x: x[1], reverse=True)
top_k = 5
for img, s in scores[:top_k]:
    print(img, s)

# Đường dẫn ảnh
path = "/content/drive/MyDrive/text_img/imgresize/3758175529_81941e7cc9.jpg"

"""PHẦN TRUY VẤN ẢNH BẰNG CẢ TEXT VÀ IMAGE"""

def combine_query(text_vec=None, image_vec=None, alpha=0.6):
    """
    alpha = trọng số text
    (1-alpha) = trọng số ảnh

    Nếu chỉ có text hoặc chỉ có ảnh → tự xử lý.
    """
    if text_vec is not None and image_vec is not None:
        combined = alpha * text_vec + (1 - alpha) * image_vec
    elif text_vec is not None:
        combined = text_vec
    else:
        combined = image_vec

    combined = combined / np.linalg.norm(combined)
    return combined

# Hàm tiền sử lý ảnh đầu vào
import cv2
def preprocess_image(image_path):

    try:
        # Mở và chuyển đổi ảnh sang định dạng RGB
        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        h, w = image.shape[:2]

        # tạo ảnh nền vuông có cạnh bằng max(h, w)
        size = max(h, w)
        square = np.zeros((size, size, 3), dtype=np.uint8)

        # tính offset để căn giữa
        y_offset = (size - h) // 2
        x_offset = (size - w) // 2

        # chèn ảnh gốc vào
        square[y_offset:y_offset+h, x_offset:x_offset+w] = image
        # resize
        inputs = cv2.resize(square, (224, 224))



        return inputs
    except Exception as e:
        print(f"Lỗi khi tiền xử lý ảnh {image_path}: {e}")
        return None

# Ví dụ sử dụng
# image_path = "/content/drive/MyDrive/dataset/messi/img_1.jpg"
# processed_image = preprocess_image(image_path)
# if processed_image:
#     print("Ảnh đã được tiền xử lý thành công!")

text_query = "đây là text_query"
text_vec = extract_text_features(text_query)
path_img = "đây là đường dẫn ảnh query"
image_vec = extract_image_features(path_img)
combined_vec = combine_query(text_vec, image_vec)
scores = []
for img_path, img_vec in loaded.items():
    img_vec = img_vec.reshape(1, -1)
    score = float(cosine_similarity([img_vec], [combined_vec]))
    scores.append((img_path, score))

scores.sort(key=lambda x: x[1], reverse=True)
top_k = 5
for img, s in scores[:top_k]:
    print(img, s)

pp = "/content/drive/MyDrive/text_img/imgresize/3280672302_2967177653.jpg"

"""END"""

# 1. Cài đặt thư viện Server & Tunnel
!pip install fastapi uvicorn pyngrok python-multipart nest-asyncio deep-translator

# 2. Kết nối với Model và Database đã load sẵn
import sys

# Kiểm tra xem bạn đã chạy các cell bên trên chưa
if 'model' not in globals() or 'processor' not in globals():
    print("❌ LỖI: Bạn chưa chạy các cell load Model bên trên. Hãy chạy lại notebook từ đầu!")
elif 'loaded' not in globals():
    print("❌ LỖI: Bạn chưa chạy cell load Database (biến 'loaded').")
else:
    # Map biến 'loaded' của bạn sang tên 'vectors_db' để Server dùng
    vectors_db = loaded

    print(f"✅ Đã kết nối Model CLIP (Device: {model.device})")
    print(f"✅ Đã kết nối Database: {len(vectors_db)} vectors")
    print("🚀 Sẵn sàng khởi động Server!")

# Cell 3: Khởi tạo FastAPI Server (Đã Fix lỗi 'Image object has no attribute read')
from fastapi import FastAPI, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from deep_translator import GoogleTranslator
import io
import base64
import numpy as np
import torch
from PIL import Image

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

translator = GoogleTranslator(source='auto', target='en')

def image_to_base64(path):
    try:
        if not os.path.exists(path): return None
        with open(path, "rb") as img_file:
            return "data:image/jpeg;base64," + base64.b64encode(img_file.read()).decode('utf-8')
    except:
        return None

@app.post("/predict")
async def predict(
    file: UploadFile = File(None),
    query: str = Form(None),
    alpha: float = Form(0.5)
):
    print(f"📥 Nhận request: Text='{query}', Ảnh={'Có' if file else 'Không'}")

    text_vec = None
    image_vec = None

    try:
        # 1. Xử lý Text
        if query:
            translated = translator.translate(query)
            print(f"   Dịch: '{query}' -> '{translated}'")
            # Hàm này OK vì nó nhận string
            text_vec = extract_text_features(translated)

        # 2. Xử lý Ảnh (FIX LỖI TẠI ĐÂY)
        if file:
            content = await file.read()
            pil_img = Image.open(io.BytesIO(content)).convert("RGB")

            # --- CODE SỬA ĐỔI: Trích xuất vector trực tiếp ---
            # Thay vì gọi extract_image_features(pil_img), ta chạy lệnh transform trực tiếp
            img_tensor = transform(pil_img).unsqueeze(0).to(device)
            with torch.no_grad():
                feat = model.get_image_features(pixel_values=img_tensor)

            # Chuẩn hóa vector
            feat = feat / feat.norm(p=2, dim=-1, keepdim=True)
            image_vec = feat.cpu().numpy()
            print("   -> Đã tạo vector ảnh thành công")

        # 3. Kết hợp (Hybrid Search)
        if text_vec is not None or image_vec is not None:
            # Chuyển đổi về tensor để dùng hàm combine (nếu cần) hoặc cộng trực tiếp numpy
            # Để đơn giản và khớp với hàm combine_query cũ, ta ép kiểu về Tensor nếu hàm đó yêu cầu,
            # hoặc tính toán thủ công ngay tại đây để an toàn nhất:

            v1 = text_vec if text_vec is not None else np.zeros((1, 512))
            v2 = image_vec if image_vec is not None else np.zeros((1, 512))

            # Nếu cả 2 đều có dữ liệu
            if text_vec is not None and image_vec is not None:
                final_vec = alpha * v1 + (1 - alpha) * v2
            elif text_vec is not None:
                final_vec = v1
            else:
                final_vec = v2

            # Chuẩn hóa lần cuối
            norm = np.linalg.norm(final_vec)
            if norm > 0:
                final_vec = final_vec / norm

            # Đảm bảo shape đúng (1, 512)
            final_vec = final_vec.reshape(1, -1)

            # 4. Tìm kiếm
            scores = []
            for path, vec in vectors_db.items():
                vec = vec.reshape(1, -1)
                # Tính Cosine Similarity
                score = np.dot(final_vec, vec.T).item()
                scores.append((path, float(score)))

            scores.sort(key=lambda x: x[1], reverse=True)

            results = []
            for path, score in scores[:5]:
                b64 = image_to_base64(path)
                if b64: results.append({"image": b64, "score": score})

            print(f"✅ Trả về {len(results)} kết quả")
            return {"top5": results}

    except Exception as e:
        print(f"❌ Lỗi: {e}")
        import traceback
        traceback.print_exc() # In chi tiết lỗi ra log Colab để debug
        return {"error": str(e)}

    return {"error": "Không có dữ liệu đầu vào"}

# Chạy Server và Public qua Ngrok
import uvicorn
import nest_asyncio
from pyngrok import ngrok

# --- ĐIỀN TOKEN CỦA BẠN VÀO ĐÂY ---
NGROK_TOKEN = "35txrgcicOrnCwU6m0F6zWoDvm6_3uaLFqCTzWNyqmnCgDCCx"
ngrok.set_auth_token(NGROK_TOKEN)

# Mở tunnel port 8000
ngrok_tunnel = ngrok.connect(8000)
print('🚀 PUBLIC URL CỦA BẠN:', ngrok_tunnel.public_url)
print('👉 Hãy copy URL này dán vào file config.py ở backend!')

# Chạy server
nest_asyncio.apply()

# Cấu hình server thủ công
config = uvicorn.Config(app, host="0.0.0.0", port=8000)
server = uvicorn.Server(config)

# Chạy server bằng await (tương thích với Colab)
await server.serve()